%%% Chang Fang Machine After 4 months

stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-007'); astOneGroupVelTestOut(1).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-041'); astOneGroupVelTestOut(2).stOneGroupVelTestOut = stOneGroupVelTestOut;
% stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-042_'); astOneGroupVelTestOut(3).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-043'); astOneGroupVelTestOut(3).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-044'); astOneGroupVelTestOut(4).stOneGroupVelTestOut = stOneGroupVelTestOut;
% stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-045_'); astOneGroupVelTestOut(6).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-049'); astOneGroupVelTestOut(5).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-050'); astOneGroupVelTestOut(6).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-056'); astOneGroupVelTestOut(7).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-057'); astOneGroupVelTestOut(8).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-058'); astOneGroupVelTestOut(9).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Customer\ChangFang_13V\13V-059'); astOneGroupVelTestOut(10).stOneGroupVelTestOut = stOneGroupVelTestOut;
batch_save_xls_group_vel_step_test(astOneGroupVelTestOut);

%%% Delivery performance check on 13Apr2012
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\WB13V_Ship_Spectrum');
test_group_get_wb_bh_wvfrm_perfrm_index_save_xls('I:\BE_WB_Data_Spectrum\BH_study\WB13V_Ship_Waveform');

%%% Velocity Loop Response
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-68');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-69');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-70');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-71');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-73');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-74');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-75');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-76');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-78');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-79');

test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-68');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-69');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-70');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-71');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-73');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-74');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-75');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-76');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-78');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-79');

test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-68');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-69');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-70');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-71');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-73');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-74');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-75');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-76');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-78');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-79');


%%% Velocity Loop Response
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-055');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049');

test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-021');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-023');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13v-024');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-025');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-027');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-028');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-029');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-030');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-031');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-032');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-033');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-034');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-035');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-036');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-037');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-038');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-039');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-040');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-041');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-042');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-043');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-044');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-009');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_MLS');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_002-14_5CUP');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_002_5Cup_00');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_03-21');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-001');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-002');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-003');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-004');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-005');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-006');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-007');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-008');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-010');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-011');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-012');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-013');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-014');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-015');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-016');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-017');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-018');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-019');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-020');
test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-015_5CUP');

stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-055\出机参数'); astOneGroupVelTestOut(1).stOneGroupVelTestOut = stOneGroupVelTestOut; astOneGroupVelTestOut(1).strCaseName = '13V-055出机参数'
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054\出机参数'); astOneGroupVelTestOut(2).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053\出机参数'); astOneGroupVelTestOut(3).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052\出机参数'); astOneGroupVelTestOut(4).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051\出机参数'); astOneGroupVelTestOut(5).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050\出机参数'); astOneGroupVelTestOut(6).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049\出机参数'); astOneGroupVelTestOut(7).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-045\出机参数'); astOneGroupVelTestOut(8).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-044\出机参数'); astOneGroupVelTestOut(9).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-043\出机参数'); astOneGroupVelTestOut(10).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-042\出机参数'); astOneGroupVelTestOut(11).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-041\出机参数'); astOneGroupVelTestOut(12).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-040\出机参数'); astOneGroupVelTestOut(13).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-039\出机参数'); astOneGroupVelTestOut(14).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-038\出机参数'); astOneGroupVelTestOut(15).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-037\出机参数'); astOneGroupVelTestOut(16).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-036\出机参数'); astOneGroupVelTestOut(17).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-034\出机参数'); astOneGroupVelTestOut(18).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-033\出机参数'); astOneGroupVelTestOut(19).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-032\出机参数'); astOneGroupVelTestOut(20).stOneGroupVelTestOut = stOneGroupVelTestOut;
stOneGroupVelTestOut = test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-027\出机参数'); astOneGroupVelTestOut(21).stOneGroupVelTestOut = stOneGroupVelTestOut;
batch_save_xls_group_vel_step_test(astOneGroupVelTestOut);

test_group_make_vel_loop_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-012');

%%%%%% 出机Spectrum
%% 13V BEI-503-2
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-010');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-013');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-016');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-017');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-018');

test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-055\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-045\出机参数');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054\');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-045');

test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-021');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-023');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13v-024');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-025');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-027');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-028');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-029');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-030');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-031');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-032');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-033');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-034');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-035');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-036');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-037');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-038');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-039');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-040');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-041');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-042');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-043');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-044');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-045');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-009');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_MLS');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_002-14_5CUP');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_002_5Cup_00');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_03-21');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-011');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-012');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-014');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-015');

test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-001');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-002');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-003');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-004');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-005');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-006');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-007');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-008');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-015_5CUP');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-020');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-019');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052');
test_group_make_spectrum_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-055');

%%%% 出机参数, 
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-055\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054\');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-045\出机参数');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-045');

test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-049');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-021');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-023');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13v-024');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-025');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-027');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-028');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-029');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-030');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-031');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-032');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-033');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-034');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-035');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-036');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-037');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-038');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-039');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-040');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-041');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-042');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-043');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-044');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-045');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-009');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_MLS');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_002-14_5CUP');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_002_5Cup_00');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\WB13V_03-21');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-010');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-011');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-012');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-013');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-014');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-015');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-016');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-017');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-018');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-001');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-002');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-003');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-004');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-005');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-006');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-007');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-008');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-015_5CUP');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-020');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-019');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-050');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-051');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-054');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-053');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-052');
test_group_make_wb_bh_waveform_mstr('I:\BE_WB_Data_Spectrum\BE_WB13V\13V-055');


